import { createHash } from "node:crypto";
import {
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, sep } from "node:path";

interface ModernDocumentInput {
  readonly rust?: { readonly moduleLayout: string };
  readonly typescript?: { readonly moduleLayout: string; readonly codeRepresentation: string };
}

/** The legacy schema_version = 1 document that T-08 accepts today. */
export function legacyDocument(moduleLayout = "file"): string {
  return `schema_version = 1\n[rust]\nmodule_layout = "${moduleLayout}"\n`;
}

/** The new versioned document under test. Spelling lives here so every test reads the same format. */
export function modernDocument(selection: ModernDocumentInput): string {
  const languages = [...(selection.rust ? ["rust"] : []), ...(selection.typescript ? ["typescript"] : [])];
  const lines = ["schema_version = 2", `languages = [${languages.map((name) => `"${name}"`).join(", ")}]`];
  if (selection.rust) lines.push("", "[rust]", `module_layout = "${selection.rust.moduleLayout}"`);
  if (selection.typescript)
    lines.push(
      "",
      "[typescript]",
      `module_layout = "${selection.typescript.moduleLayout}"`,
      `code_representation = "${selection.typescript.codeRepresentation}"`,
    );
  return `${lines.join("\n")}\n`;
}

/** Files a migration must never touch: sources, generated code, canonical model, aggregate mapping, layer declaration. */
export function untouchableUserFiles(): Record<string, string> {
  return {
    "Cargo.toml": '[package]\nname = "billing"\nversion = "0.1.0"\nedition = "2021"\n',
    "src/lib.rs": "mod invoice;\n",
    "src/invoice.rs": "pub struct Invoice;\n",
    "src/generated/schema.rs": "// generated by the code generator\npub struct Generated;\n",
    "construction/code-generation/ddd-domain-model.md": "# Domain model\n\n- ENT-001 Invoice\n",
    "construction/code-generation/ddd-aggregate-mapping.md":
      "# Aggregate mapping\n\n```yaml ddd-aggregate-mapping\naggregates:\n" +
      "  - aggregate_ref: AGG-001\n    programming_model: class\n    persistence_method: state-stored\n```\n",
    "construction/ci-pipeline/cicd-pipeline.md": "# Layer structure\n\n```yaml ddd-layer-structure\nlayers: []\n```\n",
  };
}

function createWorkspace(files: Record<string, string>): string {
  const root = mkdtempSync(join(tmpdir(), "ddd-project-settings-"));
  for (const [path, content] of Object.entries(files)) {
    const full = join(root, path);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content);
  }
  return root;
}

export function withWorkspace<T>(files: Record<string, string>, body: (root: string) => T): T {
  const root = createWorkspace(files);
  try {
    return body(root);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

/** Byte-level census of every entry below the root, so "unchanged" means unchanged and not merely re-parsed. */
export function snapshotBytes(root: string): Record<string, string> {
  const census: Record<string, string> = {};
  const walk = (directory: string): void => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const full = join(directory, entry.name);
      const key = relative(root, full).split(sep).join("/");
      if (entry.isSymbolicLink()) census[key] = `symlink:${readlinkSync(full)}`;
      else if (entry.isDirectory()) {
        census[key] = "directory";
        walk(full);
      } else census[key] = `sha256:${createHash("sha256").update(readFileSync(full)).digest("hex")}`;
    }
  };
  walk(root);
  return census;
}

export function withoutRootDocument(census: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(census).filter(([path]) => path !== ".ddd.toml"));
}
