import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ALL_CASES } from "../tests/golden/catalog.ts";
import {
  COVERAGE,
  coverageProblems,
  declaredContract,
  gateCases,
  violations,
} from "../tests/golden/contract/coverage.ts";

const root = join(import.meta.dir, "..");
export function coverageDocument(japanese: boolean): string {
  const total = COVERAGE.length;
  const sensors = declaredContract().size;
  const preempted = COVERAGE.filter((row) => row.preempted).length;
  const rows = [...COVERAGE].sort((a, b) => `${a.sensor}/${a.rule}`.localeCompare(`${b.sensor}/${b.rule}`, "en"));
  const lines = japanese
    ? [
        "# センサー契約のテスト対応表",
        "",
        "[English](sensor-coverage.md) | 日本語",
        "",
        "この表は `bun scripts/report-sensor-coverage.ts --write` で生成する。変更元は [契約表](../../tests/golden/contract/coverage.ts) と [ケース一覧](../../tests/golden/catalog.ts)。手作業で件数を更新しない。",
        "",
        `対象は${sensors}センサー・${total}規則項目。${total - preempted}項目は対応する所見を直接検証し、${preempted}項目はローダーによる先行拒否を検証する。配布物では${ALL_CASES.length}ケースを各環境で実行する。承認経路には、この表から選んだ${gateCases().length}入力を各環境で通す。`,
        "",
        "規則IDが同じでも、別センサーのケースで検証済みとは扱わない。正常例は対象構造を持つ入力、境界例は対象外・最小件数・別表記・別経路などの区別を確認する入力として選ぶ。この表は宣言した検査契約への対応を示し、Rustの全構文・業務上の意味・全分岐の網羅を保証しない。",
        "",
        "## 規則ごとの正常・異常・境界条件",
        "",
        "ケース名はセンサー内で一意。異常欄には期待する規則を含むケースをすべて列挙する。先行拒否の2項目は、代わりに実際に発生する規則を明記する。",
        "",
        "| センサー / 規則 | 正常例 | 異常例 | 境界例と根拠 |",
        "|---|---|---|---|",
      ]
    : [
        "# Sensor contract coverage matrix",
        "",
        "English | [Japanese](sensor-coverage.ja.md)",
        "",
        "Generated by `bun scripts/report-sensor-coverage.ts --write` from the [contract matrix](../../tests/golden/contract/coverage.ts) and [case catalog](../../tests/golden/catalog.ts). Do not edit counts manually.",
        "",
        `Scope: ${sensors} sensors and ${total} rule entries. ${total - preempted} entries directly exercise their findings; ${preempted} verify earlier loader rejection. Each distribution runs ${ALL_CASES.length} cases. Admission tests run ${gateCases().length} selected inputs from this matrix per harness.`,
        "",
        "A case from another sensor cannot cover a shared rule ID. Positive cases contain the relevant structure; boundary cases distinguish exclusions, minimum cardinality, alternate forms, or alternate paths. This matrix traces the declared inspection contract; it does not prove coverage of all Rust syntax, business semantics, or implementation branches.",
        "",
        "## Positive, negative, and boundary evidence",
        "",
        "Case names are unique within a sensor. The negative column lists all cases expecting that rule. The two preempted entries explicitly name the rule actually emitted instead.",
        "",
        "| Sensor / rule | Positive | Negative | Boundary and rationale |",
        "|---|---|---|---|",
      ];
  for (const row of rows) {
    const negative = violations(row)
      .map((entry) => `\`${entry.name}\``)
      .join("<br>");
    const preemption = row.preempted ? `<br>${japanese ? "先行拒否" : "Preempted by"}: \`${row.preempted.by}\`` : "";
    lines.push(
      `| ${row.sensor}<br>\`${row.rule}\` | \`${row.normal}\` | ${negative}${preemption} | \`${row.boundary}\`<br>${row.reason[japanese ? "ja" : "en"]} |`,
    );
  }
  lines.push(
    "",
    japanese ? "## 承認経路と対象外" : "## Admission coverage and exclusions",
    "",
    japanese
      ? "承認開始のテストは、対象センサーの発火・正常／異常の監査記録・異常時の規則IDを確認する。blocking所見は承認開始を拒否し、advisory所見は記録したうえで通過する。規則ごとのテストは対象センサーを単独で合成し、既存の結合テストではDDDセンサーをまとめて有効にする。無関係な成果物は補助入力を置き、Q&A・レビュー証跡はテスト設定で除外する。"
      : "Admission tests assert the target sensor's fired/terminal audit records and finding rule IDs. Blocking findings reject admission; advisory findings are recorded while admission succeeds. Per-rule tests isolate the target sensor; existing combined tests retain all DDD sensors. Unrelated artifacts receive supporting inputs, and Q&A/reviewer evidence is disabled through test settings.",
    "",
    japanese
      ? "層の依存方向は、domain・use-case・インターフェイスアダプタ・rmuを起点に6層への依存をuse/Cargoの両方で検証し、外部I/Oの許可・禁止も確認する。技術分類の予約名14種類は設計・コード両方で違反ケースを持つ。英日見出しの互換性テストもtest:sandboxに含める。"
      : "Dependency cases cover domain, use-case, Interface Adapter, and rmu sources against six destination layers through both use paths and Cargo declarations, plus external I/O permissions. All 14 reserved package names have design and code violations. test:sandbox also includes English/Japanese heading compatibility tests.",
    "",
    japanese
      ? "標準AI-DLCの単独完了ガードの再現1件は任意実行のまま残る。新規導入・更新・モデルによる生成・生成アプリケーションの動作は、この検証の対象外。[残作業](completion-tasks.ja.md)を参照。"
      : "The standard AI-DLC standalone completion-guard reproduction remains opt-in. Fresh installation, updates, model-driven generation, and generated-application behavior are outside this verification. See [remaining work](completion-tasks.md).",
    "",
  );
  return lines.join("\n");
}
export function reportProblems(): string[] {
  const problems = coverageProblems();
  for (const japanese of [false, true]) {
    const path = join(root, "docs", "developers", `sensor-coverage${japanese ? ".ja" : ""}.md`);
    if (!existsSync(path) || readFileSync(path, "utf8") !== coverageDocument(japanese))
      problems.push(`Coverage document drift: ${path}`);
  }
  return problems;
}
if (import.meta.main) {
  const problems = coverageProblems();
  if (problems.length > 0) throw new Error(problems.join("\n"));
  if (process.argv.includes("--write")) {
    for (const japanese of [false, true])
      writeFileSync(
        join(root, "docs", "developers", `sensor-coverage${japanese ? ".ja" : ""}.md`),
        coverageDocument(japanese),
      );
  } else if (reportProblems().length > 0) throw new Error(reportProblems().join("\n"));
  console.log(
    JSON.stringify({
      sensors: declaredContract().size,
      rules: COVERAGE.length,
      preempted: COVERAGE.filter((row) => row.preempted).length,
      distribution_cases: ALL_CASES.length,
      admission_cases_per_harness: gateCases().length,
    }),
  );
}
